### ISSUE TITLE
No definition for Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii-demo#10]
After installing the project in dev mode and running web server:

```
composer create-project --stability=dev --prefer-dist yiisoft/yii-demo myapp
cd myapp/public
php -S 0.0.0.0:8080
```

I got an exception:
```
Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for Psr\Log\LoggerInterface in /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php:134
Stack trace:
#0 /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php(120): Yiisoft\Di\Container->buildPrimitive('Psr\\Log\\LoggerI...', Array)
#1 /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php(111): Yiisoft\Di\Container->buildInternal('Psr\\Log\\LoggerI...', Array)
#2 /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php(79): Yiisoft\Di\Container->build('Psr\\Log\\LoggerI...', Array)
#3 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ClassDefinition.php(31): Yiisoft\Di\Container->get('Psr\\Log\\LoggerI...')
#4 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(63): Yiisoft\Factory\Definitions\ClassDefinition->resolve(Object(Yiisoft\Di\Container))
#5 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(47): Yiisoft\Factory\Def in /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php on line 134
```

Tried to dig into `Container` and `ArrayBuilder` classes but nothing worked out.

How can I run demo web app?

**Comment by maximal** [comment]
@samdark, hm, curiously, `yii` command does not work also:

```
$ cd myapp/
$ ./vendor/bin/yii serve
PHP Fatal error:  Uncaught ReflectionException: Class commands does not exist in /home/maximal/project/myapp/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php:22
Stack trace:
#0 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php(22): ReflectionClass->__construct('commands')
#1 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(78): Yiisoft\Factory\Resolvers\ClassNameResolver->resolveConstructor('commands')
#2 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(18): Yiisoft\Factory\Definitions\ArrayBuilder->getDependencies('commands')
#3 /home/maximal/project/myapp/vendor/yiisoft/factory/src/Definitions/ArrayDefinition.php(74): Yiisoft\Factory\Definitions\ArrayBuilder->build(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definitions\ArrayDefinition))
#4 /home/maximal/project/myapp/vendor/yiisoft/di/src/Container.php(123): Yiisoft\Factory\Definitions\ArrayDefinition->resolve(Object(Yiisoft\Di\Container), Array)
#5  in /home/maximal/project/myapp/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php on line 22
```

**Comment by samdark** [comment]
Definition fixed. Console is in progress...

**Comment by samdark** [comment]
Works now.
