### ISSUE TITLE
/vendor/bin/yii serve error

### ISSUE THREAD

**Issue by alexkart** [yiisoft/yii-demo#12]
### What steps will reproduce the problem?
Steps from the guide (https://github.com/yiisoft/docs/blob/master/guide/en/start/installation.md):

```bash
composer create-project --prefer-dist --stability=dev yiisoft/yii-demo yii3-app
cd yii3-app/public
../vendor/bin/yii serve
```

### What is the expected result?
Web server started

### What do you get instead?
```
PHP Fatal error:  Uncaught ReflectionException: Class commands does not exist in /vagrant/yii3-app/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php:22
Stack trace:
#0 /vagrant/yii3-app/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php(22): ReflectionClass->__construct('commands')
#1 /vagrant/yii3-app/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(78): Yiisoft\Factory\Resolvers\ClassNameResolver->resolveConstructor('commands')
#2 /vagrant/yii3-app/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(18): Yiisoft\Factory\Definitions\ArrayBuilder->getDependencies('commands')
#3 /vagrant/yii3-app/vendor/yiisoft/factory/src/Definitions/ArrayDefinition.php(74): Yiisoft\Factory\Definitions\ArrayBuilder->build(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definitions\ArrayDefinition))
#4 /vagrant/yii3-app/vendor/yiisoft/di/src/Container.php(123): Yiisoft\Factory\Definitions\ArrayDefinition->resolve(Object(Yiisoft\Di\Container), Array)
#5 /vagrant/yii3-app/vendor/yiisoft/di/src/Container.php(111):  in /vagrant/yii3-app/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php on line 22

```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.3
| Operating system | Ubuntu 18.04

**Comment by samdark** [comment]
Yes. That's know thing connected with composer-config plugin. @hiqsol is on it.

**Comment by samdark** [comment]
https://github.com/hiqdev/composer-config-plugin/issues/31

**Comment by samdark** [comment]
Fixed.
