### ISSUE TITLE
Error on incorrect username password

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/yii-demo#187]
```
TypeError: Argument 2 passed to Yiisoft\Yii\Debug\Collector\LogCollector::collect() must be of the type string, object given, called in /demo/vendor/yiisoft/yii-debug/src/Proxy/LoggerInterfaceProxy.php on line 42 and defined in /demo/vendor/yiisoft/yii-debug/src/Collector/LogCollector.php:18
Stack trace:
#0 /demo/vendor/yiisoft/yii-debug/src/Proxy/LoggerInterfaceProxy.php(42): Yiisoft\Yii\Debug\Collector\LogCollector->collect()
#1 /demo/src/Controller/AuthController.php(75): Yiisoft\Yii\Debug\Proxy\LoggerInterfaceProxy->error()
#2 [internal function]: App\Controller\AuthController->login()
#3 /demo/vendor/yiisoft/injector/src/Injector.php(63): ReflectionFunction->invokeArgs()
#4 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareFactory.php(69): Yiisoft\Injector\Injector->invoke()
#5 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): class@anonymous->process()
#6 /demo/vendor/yiisoft/data-response/src/Middleware/FormatDataResponse.php(25): class@anonymous->handle()
#7 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\DataResponse\Middleware\FormatDataResponse->process()
#8 /demo/vendor/yiisoft/yii-debug-api/src/Middleware/DebugHeaders.php(31): class@anonymous->handle()
#9 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\Yii\Debug\Api\Middleware\DebugHeaders->process()
#10 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(51): class@anonymous->handle()
#11 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(39): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle()
#12 /demo/vendor/yiisoft/router/src/MatchingResult.php(81): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch()
#13 /demo/vendor/yiisoft/router/src/Middleware/Router.php(46): Yiisoft\Router\MatchingResult->process()
#14 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\Router\Middleware\Router->process()
#15 /demo/vendor/yiisoft/session/src/SessionMiddleware.php(34): class@anonymous->handle()
#16 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\Session\SessionMiddleware->process()
#17 /demo/vendor/yiisoft/csrf/src/CsrfMiddleware.php(49): class@anonymous->handle()
#18 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\Csrf\CsrfMiddleware->process()
#19 /demo/vendor/yiisoft/error-handler/src/ErrorCatcher.php(131): class@anonymous->handle()
#20 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(87): Yiisoft\ErrorHandler\ErrorCatcher->process()
#21 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(51): class@anonymous->handle()
#22 /demo/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(39): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle()
#23 /demo/vendor/yiisoft/yii-web/src/Application.php(57): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch()
#24 /demo/public/index.php(62): Yiisoft\Yii\Web\Application->handle()
#25 {main}
```

**Comment by samdark** [comment]
@Mister-42 I've merged some code updates. Please re-check. Thanks.

**Comment by Mister-42** [comment]
Got the exact same error after a fresh install :(

**Comment by samdark** [comment]
Should be fixed now. Please do composer update and re-check.

**Comment by Mister-42** [comment]
Confirmed! Thank you very much.
