### ISSUE TITLE
Demo fails with No definition for Yiisoft\Middleware\Dispatcher\MiddlewarePipelineInterface

### ISSUE THREAD

**Issue by morrisonlevi** [yiisoft/yii-demo#268]
### What steps will reproduce the problem?

```bash
git clone https://github.com/yiisoft/yii-demo.git
cd yii-demo
composer update
./vendor/bin/yii serve &
curl 0.0.0.0:8080 # this has the exception
```
### What is the expected result?
The demo works

### What do you get instead?
An exception

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.0.3
| Operating system | Debian 10 "buster"

Full trace;
```
Yiisoft\Factory\Exceptions\NotFoundException: No definition for Yiisoft\Middleware\Dispatcher\MiddlewarePipelineInterface in /srv/yii-demo/vendor/yiisoft/proxy/src/ProxyTrait.php:20
Stack trace:
#0 /srv/yii-demo/vendor/yiisoft/yii-debug/src/Proxy/ContainerInterfaceProxy.php(62): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->repeatError(Object(Yiisoft\Factory\Exceptions\NotFoundException))
#1 /srv/yii-demo/src/ApplicationRunner.php(63): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->get('Yiisoft\\Yii\\Web...')
#2 /srv/yii-demo/public/index.php(24): App\ApplicationRunner->run()
#3 {main}
```

**Comment by vjik** [comment]
Fixed via https://github.com/yiisoft/yii-demo/commit/815bb6dcda44f7b095a6f32bdfd3162c6c839f8b
