### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by freekup** [yiisoft/yii-demo#83]
Recently I installed the latest development version from composer with `composer create-project --prefer-dist --stability=dev yiisoft/yii-demo app` command. I got this error when running `"vendor/bin/yii" serve`
```
PHP Notice:  Undefined index: container in D:\Project\app\vendor\yiisoft\yii-console\bin\yii on line 43

Notice: Undefined index: container in D:\Project\app\vendor\yiisoft\yii-console\bin\yii on line 43
PHP Fatal error:  Uncaught Error: Function name must be a string in D:\Project\app\vendor\yiisoft\yii-console\bin\yii:43
Stack trace:
#0 D:\Project\app\vendor\yiisoft\yii-console\bin\yii(46): {closure}()
#1 {main}
  thrown in D:\Project\app\vendor\yiisoft\yii-console\bin\yii on line 43

Fatal error: Uncaught Error: Function name must be a string in D:\Project\app\vendor\yiisoft\yii-console\bin\yii:43
Stack trace:
#0 D:\Project\app\vendor\yiisoft\yii-console\bin\yii(46): {closure}()
#1 {main}
  thrown in D:\Project\app\vendor\yiisoft\yii-console\bin\yii on line 43
```

After that, I tried to run on Apache2, this is my apache configuration
```
<VirtualHost *:80>
    DocumentRoot "D:\Project\app\public"
    ServerName yii.test.local

    <Directory "D:\Project\app\public">
        Options Indexes FollowSymLinks Includes ExecCGI
        #Options FollowSymLinks Multiviews Indexes
        AllowOverride All
	Order deny,allow
    	Allow from all
        Require all granted
    </Directory>
</VirtualHost>
```

I got this error

```
Fatal error: Uncaught InvalidArgumentException: Invalid path alias: @runtime/logs/app.log in D:\Project\app\vendor\yiisoft\aliases\src\Aliases.php:141 Stack trace: #0 D:\Project\app\src\Factory\LoggerFactory.php(17): Yiisoft\Aliases\Aliases->get('@runtime/logs/a...') #1 D:\Project\app\vendor\yiisoft\factory\src\Definitions\CallableDefinition.php(19): App\Factory\LoggerFactory->__invoke(Object(Yiisoft\Di\Container)) #2 D:\Project\app\vendor\yiisoft\di\src\Container.php(214): Yiisoft\Factory\Definitions\CallableDefinition->resolve(Object(Yiisoft\Di\Container)) #3 D:\Project\app\vendor\yiisoft\di\src\Container.php(155): Yiisoft\Di\Container->buildInternal('Psr\\Log\\LoggerI...') #4 D:\Project\app\vendor\yiisoft\di\src\Container.php(88): Yiisoft\Di\Container->build('Psr\\Log\\LoggerI...') #5 D:\Project\app\vendor\yiisoft\factory\src\Definitions\ClassDefinition.php(36): Yiisoft\Di\Container->get('Psr\\Log\\LoggerI...') #6 D:\Project\app\vendor\yiis in D:\Project\app\vendor\yiisoft\aliases\src\Aliases.php on line 141
```

I tried to run `composer dump-autoload`, and got this error when running on browser

```
Fatal error: Uncaught RuntimeException: Alias of the root directory is not defined. in D:\Project\app\runtime\build\config\web.php:58 Stack trace: #0 D:\Project\app\vendor\yiisoft\factory\src\Definitions\CallableDefinition.php(19): {closure}(Object(Yiisoft\Di\CompositeContainer)) #1 D:\Project\app\vendor\yiisoft\di\src\Container.php(214): Yiisoft\Factory\Definitions\CallableDefinition->resolve(Object(Yiisoft\Di\CompositeContainer)) #2 D:\Project\app\vendor\yiisoft\di\src\Container.php(155): Yiisoft\Di\Container->buildInternal('Yiisoft\\Yii\\Fil...') #3 D:\Project\app\vendor\yiisoft\di\src\Container.php(88): Yiisoft\Di\Container->build('Yiisoft\\Yii\\Fil...') #4 D:\Project\app\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(171): Yiisoft\Di\Container->get('Yiisoft\\Yii\\Fil...') #5 D:\Project\app\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(56): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->getInstance('Yiisoft\\Yii\\F in D:\Project\app\runtime\build\config\web.php on line 58
```

Do I have a mistake when configuring?

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.4
| Operating system | Windows 10

**Comment by samdark** [comment]
Run `composer du` once. We're aware of it: https://github.com/yiisoft/composer-config-plugin/issues/21

**Comment by freekup** [comment]
I got the same error like this after reinstalling, and running `composer du` command

```
Fatal error: Uncaught RuntimeException: Alias of the root directory is not defined. in D:\Project\app\runtime\build\config\web.php:58 Stack trace: #0 D:\Project\app\vendor\yiisoft\factory\src\Definitions\CallableDefinition.php(19): {closure}(Object(Yiisoft\Di\CompositeContainer)) #1 D:\Project\app\vendor\yiisoft\di\src\Container.php(214): Yiisoft\Factory\Definitions\CallableDefinition->resolve(Object(Yiisoft\Di\CompositeContainer)) #2 D:\Project\app\vendor\yiisoft\di\src\Container.php(155): Yiisoft\Di\Container->buildInternal('Yiisoft\\Yii\\Fil...') #3 D:\Project\app\vendor\yiisoft\di\src\Container.php(88): Yiisoft\Di\Container->build('Yiisoft\\Yii\\Fil...') #4 D:\Project\app\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(171): Yiisoft\Di\Container->get('Yiisoft\\Yii\\Fil...') #5 D:\Project\app\vendor\yiisoft\yii-debug\src\Proxy\ContainerInterfaceProxy.php(56): Yiisoft\Yii\Debug\Proxy\ContainerInterfaceProxy->getInstance('Yiisoft\\Yii\\F in D:\Project\app\runtime\build\config\web.php on line 58
```

**Comment by freekup** [comment]
I have fixed this problem with change `./runtime/build/config/web.php`. I moved `$params = (array) require __DIR__ . '/params.php';` in the bottom of `$_ENV = array_merge((array) require __DIR__ . '/envs.php', $_ENV);`. I also changed `'Yiisoft\\Yii\\Cycle\\Conveyor\\SchemaConveyorInterface'` from `&$params` to `$params`.
